#!/bin/sh

echo "Installing sage-base-theme"

rm -rf .git*    && \
npm install     && \
bower install   && \
gulp font       && \
gulp build      && \
rm init

echo "bc-base-theme successfully installed use gulp watch to watch files - check your manifest"
