#!/bin/sh

echo "Installing sage-base-theme"

rm -rf .git*    && \
npm install     && \
bower install   && \
gulp fonts       && \
gulp build      && \
rm init

echo "UPDATE YOUR MANIFEST FILE URL it can be found in sage/assets/manifest.json once done run gulp watch and your all done!!!! - "